version: 2.1

#Define a job to be invoked later in a workflow.
jobs:
    build:
        docker:
          - image: circleci/node:13.8.0
        steps:
          - checkout
          - run: npm install
          - save_cache:
                Key: "npm-packages"
                paths:
                  - src/node_modules
          - run: npm run lint

    test:
        docker:
          - image: circleci/node:13.8.0
        steps:
          - checkout
          - restore_cache:
                Key: "npm-packages"
                paths:
                  - src/node_modules
          - run: npm install
          - run: npm run test

    analyze:
        docker:
          - image: circleci/node:13.8.0
        steps:
          - checkout
          - restore_cache:
                Key: "npm-packages"
                paths:
                  - src/node_modules
          - run: npm install
          - run: npm audit

# Invoke jobs via workflows
workflows:
    ci-pipeline-workflow:
        jobs:
          - build
          - test:
              requires:
                - build
          - analyze:
              requires:
                - test

